language: go
sudo: required

env:
- GO111MODULE=on

script:
- go test ./...

dist: trusty

services:
  - postgresql

notifications:
  email: false

matrix:
  include:
  - addons:
      apt:
        packages:
        - rpm
      postgresql: 9.4
  - addons:
      apt:
        packages:
        - rpm
      postgresql: 9.5
  - addons:
      apt:
        packages:
        - rpm
      postgresql: 9.6
